# distutils: language = c++

DEF CYTHON_FIGHTER_PLAYER_PXD = 0
DEF CYTHON_FIGHTER_OUTLINE_PXD = 0
DEF CYTHON_FIGHTER_ANIMATION_PXD = 0
DEF CYTHON_FIGHTER_GAME_PXD = 0
DEF CYTHON_FIGHTER_MAIN_PXD = 0
DEF CYTHON_FIGHTER_MANAGERS_PXD = 0
DEF CYTHON_FIGHTER_AM_PXD = 0
DEF CYTHON_FIGHTER_SM_PXD = 0
DEF CYTHON_FIGHTER_OM_PXD = 0
DEF CYTHON_FIGHTER_KEYS_PXD = 0
DEF CYTHON_FIGHTER_UTILS_PXD = 0
DEF CYTHON_FIGHTER_COLOR_PXD = 0
DEF CYTHON_FIGHTER_PHYSICS_PXD = 0
DEF CYTHON_FIGHTER_VEC2_PXD = 0

include "main.pxd"
